# Copyright (c) 2013, Dennis Schridde <dschridde@welfenlab.de>
# Redistribution and use is allowed according to the terms of the BSD license.
# For details see the accompanying COPYING-CMAKE-SCRIPTS file.

set(CPACK_PACKAGE_VERSION_MAJOR ${VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${VERSION_PATCH})
set(CPACK_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}")
set(CPACK_PACKAGE_VENDOR ${VENDOR})
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY ${DESCRIPTION})
set(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/${WELCOME_FILE}")

#set(CPACK_PACKAGE_EXECUTABLES "...")
#set(CPACK_PACKAGE_ICON "${CMAKE_CURRENT_SOURCE_DIR}/...")

set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/${LICENSE_FILE}")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/${README_FILE}")
set(CPACK_RESOURCE_FILE_WELCOME "${CMAKE_CURRENT_SOURCE_DIR}/${WELCOME_FILE}")

set(CPACK_SOURCE_IGNORE_FILES_DEFAULT "/CVS/;/\\\\.svn/;/\\\\.bzr/;/\\\\.hg/;/\\\\.git/;\\\\.swp$;\\\\.#;/#")
set(CPACK_SOURCE_IGNORE_FILES "${CPACK_SOURCE_IGNORE_FILES_DEFAULT};/build/;/externals/;/lib/;~$")

#set(CPACK_NSIS_INSTALLED_ICON_NAME "...")
set(CPACK_NSIS_HELP_LINK "${URL}")
set(CPACK_NSIS_URL_INFO_ABOUT "${URL}")
set(CPACK_NSIS_CONTACT "${EMAIL}")

# Import CPack macros and set automatic variables
include(CPack)
